todo:
- firewall
- look into systemd-boot more
- can i ssh into live arch install to copy/paste commands?
- enforce delay and lock user out after incorrect attempts [Security]
- better passwords
- all of system maintenance
- console improvements (zsh, tab-completion, etc.)
- dns security
- hibernation
- sddm on x11?
- script creating the git dot files thing (and all of the above :))
